# == == == == == === == == == == == #
#      Prison 3 Configuration       #
# Be sure to check your formatting! #
#      This must be valid yml.      #
# == == == == == === == == == == == #
#
#  New features have been recently added to prison.  These new features can add a lot
#  of value to your server, but they may also be in the process of growing and evolving.
#  If you experiance any issues, have questions, or you have ideas on how to improve
#  upon these items, then please visit our discord server.  These new features are 
#  marked with the "NEW" tag below.
#  
#

# Note: This actually doesn't do anything. May have done something with v3.1.1 or earlier.
debug: false

# Upon server startup prison will check to see if a newer version has been released.
check-updates: true

# Provides unidentifiable metrics so we can better understand what versions of minecraft,
# spigot, server OS, and the Prison plugin version that is being used. This is used to 
# understand what versions of spigot should be supported, and which versions of prison 
# is actually being used and can greatly impact future development efforts. Enabling the 
# send-metrics would be greatly appreciatd since it will help us greatly.
# You can view the stats here: https://bstats.org/plugin/bukkit/Prison  
send-metrics: true

show-alerts: true

# NEW: Prison now has prestiges! 
# https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_107_setting_up_pestiges.md
prestiges: true

# NEW: This enables new physics to be applied when jumpping on slime blocks.
# When holding different items, like some block types or picks, the player can
# jump even higher to heights of 40 to 60+ blocks.
slime-fun: false

# NEW: Prison now has GUIs for most features and actions. For more options please check
# the GuiConfig.yml. 
# Access with /gui
prison-gui-enabled: true

# NEW: Enable or disable /mines to open the GUI to players (This won't works with OPs or
# admins who have the permission mines.admin or prison.admin)
# This command's only a shortcut of /prisonmanager mines
mines-gui-enabled: true

# NEW: Enable or disable /ranks to open the GUI to players (This won't works with OPs or
# admins who have the permission ranks.admin or prison.admin)
# This command's only a shortcut of /prisonmanager ranks
ranks-gui-enabled: true

# NEW: /ranks prestiges's a shortcut of /prisonmanager prestiges and the same as the /prestiges shortcut
ranks-gui-prestiges-enabled: true

# NEW: /prestiges command which opens the Prestiges GUI, this's basically a shortcut of the /prisonmanager prestiges
prestiges-gui-enabled: true
# There're more options for the GUIs, please edit the GuiConfig.yml


# NEW: Enable or disable the SellAll command and sub-commands
sellall: false


# Startup testing of available blocks within prison. Tests three kinds of
# sources: Prison's BlockType, XMaterial's blocks (should mirror what's avaiable
# within spigot/bukkit, and the raw spigot/bukkit source.
# This should only be used to see what's available for the current version of 
# spigot that is running on the server. This will not provide any 
# extra blocks for any prison environment.
prison-block-compatibility-report: false



default-language: en_US

# The storage engine that Prison should use to store data.
# Ensure that only one is left uncommented out. Also, ensure
# that you specify your MongoDB or SQL login credentials if necessary.
storageType: "json"
#storageType: "mongo"
#storageType: "sql"

# NOTE: The following is not used since SQL and MongoDB are not valid options.
# Login credentials for either SQL or MongoDB
#database:
#  enabled: false
#  type: sql # sql or mongo
#  host: localhost
#  database: prison
#  username: root
#  password: root
#  port: 3306
